version: "3.8"
services:
  latex:
    build: .
    volumes:
      - .:/documents
    environment:
      - SHELL=/bin/bash
      - MAIN_TEX=cv-llt.tex # Asegúrate de que el valor está definido aquí
    stdin_open: true
    tty: true
    restart: unless-stopped
    command:
      [
        "/bin/bash",
        "-c",
        "latexmk -pdf -interaction=nonstopmode -halt-on-error -outdir=build -pvc -view=none $MAIN_TEX",
      ]
